global:
  scrape_interval: 15s
  evaluation_interval: 30s
  scrape_timeout: 10s

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: "twiga-app"
    metrics_path: /metrics
    static_configs:
      - targets:
          - host.docker.internal:8000
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: twiga-app

  - job_name: "redis-exporter"
    static_configs:
      - targets:
          - redis_exporter:9121
